dbgate/dbgate

- plugins/dbgate-plugin-mysql/src/backend/Analyser.js
if somehow SHOW CREATE VIEW fails (invalid refs, permissions) it throws an
error and no structure is shown at all.
> fix: catch getViewTexts errors otherwise no structure can be seen

- app/package.json
I haven't been able to test this out yet since I'm running into issues with building on Apple Silicon (unrelated to building *for* Apple Silicon)
Opening this as a reminder to myself to test this on an Intel laptop ☺️
> add arm64 arch target for macOS

- plugins/dbgate-plugin-mysql/src/backend/Analyser.js
I don't know if it's a permission issue or somehow these views were created incorrectly, but `information_schema.tables` contains null both in `CREATE_TIME` and `UPDATE_TIME` so analyzer fails.
> fix(mysql): contentHash return null if modifyDate is not set

- plugins/dbgate-plugin-mongo/src/backend/driver.js
Fix issue where createBulkInsertStream isn't found when importing into mongo database
Function is exported like:
module.exports = createBulkInsertStream;
> Fix importing into a mongo db

- packages/web/src/widgets/TabsPanel.svelte
To fix #260
I think there's no need to change the close button to `close-button-right` since the `file-name` span would flex correctly same as `db-name`
> Fixes misplaced tab close icon

- README.md
- app/package.json
- packages/web/package.json
Is there a downside to using port 5001? Port 5000 fails on Mac because ControlCenter is listening on port 5000. I also updated the readme to reflect changes. If I am missing something let me know.
> Portchange

- packages/web/src/designer/Designer.svelte
- packages/web/src/tabs/DiagramTab.svelte
On Linux I currently do not have any toolstrip for diagram view, nor am I able to use horizontal/vertical scrollbars (they don't exist), with this they all work again, tested on Linux.
Additionally this adds zoom factor up to 200% for the diagram designer as on high DPI displays, 100% can still be relatively small.
> Fixes missing toolstrip and adds up to 200% zoom to diagram view

- docker/entrypoint.sh
Replace `entrypoint.sh` process with `node` process in final command using `exec`.
This is to pass signals to the `node` process (e.g. SIGTERM upon stopping the container).
Currently signals are ignored, because `node` is executed as subprocess of the `entrypoint.sh`.
This will allow to speed up shutting down of the container.
> Pass signals in entrypoint.sh

- packages/web/src/utility/uploadFiles.ts
This is to resolve #626 which was identified as an issue where the JWT is not passed along with an upload request when password authentication is enabled.
> add API headers on upload call

- packages/web/src/impexp/SourceTargetConfig.svelte
This PR fixes a visual issue with the query editor in the import/export screen. When selecting 'Query' as the source storage type, the query editor would overlap unnaturally with the selector.
This is caused by z-index contamination. Creating a new stacking context on the editor wrapper fixes this.
| Procedure | Screenshot |
|:-|:-:|
|1. Open the Import/Export screen. <br /> Then select 'Query' as the source storage type.| <img width="200" alt="image" src="https://github.com/dbgate/dbgate/assets/40572953/c1d40cce-1c1f-4881-a6cb-2ad603b56bd8"> |
| 2. Open Selector. <br /><br /> This happens with any selector. |  <img width="200" alt="image" src="https://github.com/dbgate/dbgate/assets/40572953/c13b4481-4aaf-4c54-83ee-8addc0fe1f34"> <br /><br />  <img width="200" alt="image" …
> fix: query editor on import/export screen overlaps with selector

- app/src/electron.js
- app/src/mainMenuDefinition.js
- packages/web/src/commands/stdCommands.ts
Closes #673 
This PR fixes a macOS keyboard shortcut for select all.
Add Select All to just macOS edit menu.
I checked the operation on MacOS and Windows (electron app and chrome) respectively. It appeared to be a bug that only occurred with Electron on MacOS.
I also checked Electron Issues and found that shortcuts sometimes do not work on Mac.
https://github.com/electron/electron/issues/3787
I have confirmed that adding the Select All shortcut to the menu solves the problem.
(I add a new menu to the Edit menu. This is for Electron. This means that the new menu item will also appear in Windows Electron.)
(Exactly the same as an issue procedure)
Environment: MacOS Electron
1. Go to any input field
2. Write some text
3. Press Command + a to select whole text
> fix: Mac - shortcut for select all

- packages/web/src/query/RunnerOutputFiles.svelte
- packages/web/src/utility/exportFileTools.ts
fixes #503, fixes #636
This PR fixes an identified issue where the JWT is not passed with a download request when password authentication is enabled.
Not only have the previously reported issues been fixed, but also the code where similar bugs occur due to the same coding.
There were four.
Environment: Docker or Web
Please set the `env` values as follows before trying each case to enable authentication.
(The value itself can be anything.)
```
LOGINS=test
LOGIN_PASSWORD_test=test
```
1. Right click on database.
2. Select `Export wizard`, then Open `Export / Import` Screen.
3. Select any `Souce configuration`.
4. Select any file as `Target configuration`.
5. Run.
6. Click `download` from OUTPUT files.
Quick Export is an export that does not use the wizard. can be accessed from the context …
> fix: download with auth header

- packages/web/src/modals/ExportDatabaseDumpModal.svelte
fixes #652 
This PR fixes a problem with incorrect folder selection.
`electron.showSaveDialog` returns file path and its type is `Promise<string>` but the code was expected `Promise<string[]>`.
> fix(app): Correctly select the save folder for dump

- packages/web/package.json
- packages/web/src/utility/openElectronFile.ts
Closes #376, Closes #634, Closes #640
This is also noted in the following comment.
https://github.com/dbgate/dbgate/issues/376#issuecomment-1841314551
When the feature to determine the encoding from a file's Byte Order Mark (BOM) was added, the encoding was determined to be `ascii` if the encoding could not be determined from the BOM.
`utf-8` is compatible with `ascii` encoding, and if a file containing only `ascii` characters is saved in `utf-8`, the binaries will be equivalent.
However, unicode characters that can be handled by `utf-8` cannot be handled by `ascii`, resulting in garbled characters.
For this reason, I have changed the encoding to be judged as `utf-8` if the encoding cannot be determined from the BOM.
Also, the file decoding process has been changed to use `iconv-lite` for …
> fix(app): Encoding error when opening Unicode query files

- plugins/dbgate-plugin-postgres/src/backend/sql/columns.js
- plugins/dbgate-plugin-postgres/src/backend/sql/tableModifications.js
This PR changes the Postgresql columns that are Composite Types, Enums or Arrays to show their proper type instead of `USER-DEFINED`.
Example:
```SQL
CREATE TYPE color AS ENUM ('red', 'green', 'blue');
CREATE TYPE condition AS ENUM ('new', 'old');
CREATE TYPE contact_type AS ENUM ('phone', 'email');
CREATE TYPE dimensions AS (
width           NUMERIC,
height          NUMERIC,
depth           NUMERIC
);
CREATE TYPE contact AS (
first_name      VARCHAR(255),
last_name       VARCHAR(255),
contact         VARCHAR(255),
contact_type    contact_type
);
CREATE TABLE cars (
id                SERIAL PRIMARY KEY, 
brand             VARCHAR(255),
model             VARCHAR(255),
year              INT,
color             color,
condition         condition,
parameters        size,
contacts …
```
> Postgresql - Show proper types for Composite Types, Enums and Arrays

- packages/api/src/controllers/connections.js
This PR adds a new environment variable `SSL_TRUST_CERTIFICATE_${id}` which is necessary to connect to a database that has a self signed cert via environment variables. It should resolve this issue https://github.com/dbgate/dbgate/issues/600
> Adding env for parsing for trustServerCertificate connection value

- packages/api/src/controllers/auth.js
- packages/api/src/main.js
- packages/api/src/utility/hasPermission.js
This PR enables the creation of permissions for users that do not have password-based login credentials defined. This is intended to be used with OAuth-based authentication, allowing for per-user authorization to be defined in dbgate, while allowing a 3rd party system to handle authentication.
I have added reference to an environment variable: `OAUTH_PERMISSIONS` which allows this authorization flow to be enabled. Without entering a truthy value for this environment variable, this workflow is disabled by default.
> feat: per-user permissions when using oauth

- packages/api/src/controllers/auth.js
Added option to have OAUTH_ALLOWED_GROUPS as comma separated value in environment config for OAUTH.
Required values in config will be:
1) OAUTH_GROUP_FIELD 
2) OAUTH_ALLOWED_GROUPS
This is similar to OAUTH_ALLOWED_LOGINS but it is for OAUTH group based.
> Added OAuth Allowed Groups Option

- packages/api/src/utility/hasPermission.js
This is a follow-up to https://github.com/dbgate/dbgate/pull/770
After testing, I found that the original implementation had issues that ultimately made the code change unusable. This is a change set to address those issues.
The original change created login entries with `null` passwords when the `OAUTH_PERMISSIONS` env var was enabled, but this presents two issues:
1. If the `LOGINS` env var is not declared, the app crashes
2. If the `LOGINS` env var _is_ declared, OAuth cannot be used
In this PR the implementation is changed, instead of creating users from `LOGINS`, read all entries of `LOGIN_PERMISSIONS_x`, and **directly create `userPermissions` entries**.
Second issue: `hasPermission` does not work with OAuth, because the `authMiddleware` method puts the user information in …
> feat: per-user permissions when using oauth, follow-up

- packages/api/src/auth/authProvider.js
Fixes #727
The response of the oauth token endpoint doesn not always contain n access_token in JWT format, in these cases a fallback to the id_token should be tried to get the payload.
> Fix 727: access_token not a jwt

- plugins/dbgate-plugin-postgres/src/frontend/drivers.js
Adding `geometry` to spatial types to allow the cell view to call `ST_AsText` on the underlying data, similar to its current handling of `geography`.
*maybe* fixes dbgate/dbgate#307
> Update postgres plugin drivers.js

- packages/api/src/controllers/connections.js
This allows passing `localDataCenter` connection property (used in Cassandra plugin) via environment variable
> feat: configure cassandra local datacenter via environment variable

- plugins/dbgate-plugin-cassandra/src/backend/driver.js
This PR adds support for Cassandra plain-text authentication  (https://github.com/datastax/nodejs-driver/tree/master/doc/features/auth). Default `NoAuth` provider is used if either `user` or `password` are missing
> feat: add support for plain-text auth for Cassandra

- docker/Dockerfile
- docker/Dockerfile-alpine
Add source label to the container. This allows services such as Renovate bot (which keeps dependencies up to date) to find the change log and include it in the PR it opens.
https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/readme.md
Here's an example of a repo that [includes the label](https://github.com/prometheus/prometheus/blob/main/Dockerfile#L5), and how it shows up in the pr (note the Release Notes).
|prometheus|dbgate|
|--|--|
|<img width="400" alt="Screenshot 2025-05-05 at 12 49 03 PM" src="https://github.com/user-attachments/assets/9101286e-3adc-4d71-b183-e9c8eeb40872" />|<img width="400" alt="Screenshot 2025-05-05 at 12 49 39 PM" src="https://github.com/user-attachments/assets/ff1bbf53-4214-4783-bd27-46ed3adf7e91" />|
> Add source label to container
